apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9jdHNlOmN0c2UxMjNAY2x1c3RlcjAuMWpzb2kubW9uZ29kYi5uZXQvcHJvZHVjdF9jdHNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw